In [91]:
import numpy as np

# ARRAY vs LIST

In [92]:
# ARRAY
array = np.array([1, 2, 3, 4, 5])
print(array)

[1 2 3 4 5]


In [93]:
# LIST
list = (1, 2, 3, 4, 5)
print(list)

(1, 2, 3, 4, 5)


% TIMEIT    --> for one line

%% TIMEIT   --> for whole program

In [94]:
%timeit [j**4 for j in range(1,9)]

755 ns ± 28.4 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [95]:
%timeit np.arange(1,9)**4

2.2 μs ± 50.4 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


# NUMPY ARRAYS

In [96]:
a = [1, 2, 3, 4, 5]

b = np.array(a)

print(b)
print(type(b))
b 
print(b.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [97]:
l = []

for i in range(1,4):
    int_1 = int(input("Enter: "))
    l.append(int_1)

print(np.array(l))

ValueError: invalid literal for int() with base 10: ''

1-D || 2-D  || 3-D ARRAYS

In [ ]:
# 1-D Array
arr1 = np.array([1, 2, 3, 4])
print(arr1.ndim)

1


In [ ]:
# 2-D Array
arr2 = np.array([[1, 2, 3, 4], [4, 5, 6, 7]])

print(arr2)
print(arr2.ndim)

[[1 2 3 4]
 [4 5 6 7]]
2


In [ ]:
# 3-D Array
arr3 = np.array([[[1, 2, 3, 4],[4, 5, 6, 7],[8, 9, 0, 6]]])

print(arr3)
print(arr3.ndim)

[[[1 2 3 4]
  [4 5 6 7]
  [8 9 0 6]]]
3


In [ ]:
# N-dim Array

arrn = np.array([1, 2, 3, 4], ndmin = 7)

print(arrn)
print(arrn.ndim)

[[[[[[[1 2 3 4]]]]]]]
7


# Creating Numpy Arrays with Numpy Functions

In [ ]:
# ZEROS

ar_zero = np.zeros(3)   # 1-D
ar_zero1 = np.zeros((3, 4))  # 2-D 
print(ar_zero)
print()
print(ar_zero1)

[0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
# ONES

ar_one = np.ones(2)
ar_one1 = np.ones((3,3))
print(ar_one)
print()
print(ar_one1)

[1. 1.]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# Empty Array

ar_empt = np.empty((3,4))
print(ar_empt)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
# Range of Elements

arr_range = np.arange(0, 10, 2)
print(arr_range)

[0 2 4 6 8]


In [ ]:
# Diagonal element filled with 1's

arr_diag = np.eye(3)
print(arr_diag)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# Diagonal element fir 3x5
arr_diag = np.eye(3, 5)
print(arr_diag)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [ ]:
# Arrays with values that are spaced linearly in a specified interval

arr_line_space = np.linspace(0, 10, num=5)
print(arr_line_space)

[ 0.   2.5  5.   7.5 10. ]


# Random Numbers

In [ ]:
# Rand()

var = np.random.rand(5)   # generates 5 random number 1-D array

print(var)        

[0.97165147 0.50077348 0.47195885 0.06572602 0.09432603]


In [ ]:
var1 = np.random.rand(2,5)  # 2-D array

print(var1)

[[0.49954068 0.56282546 0.73432857 0.80632876 0.04019329]
 [0.22394685 0.29999373 0.8215422  0.77625783 0.52444971]]


In [ ]:
# Randn()

var2 = np.random.randn(4, 3)

print(var2)

[[ 1.50301025  1.10276404 -1.25945281]
 [ 0.60973351 -0.67766304  1.17146656]
 [ 1.93305109 -1.4496177   0.68917861]
 [-0.8378518   0.4224466   0.45131726]]


In [ ]:
# ranf()

var3 = np.random.ranf((2, 3))

print(var3)

[[0.65347488 0.71799464 0.57607254]
 [0.87756355 0.46243626 0.92346984]]


In [ ]:
# randint()

var4 = np.random.randint(1,10,size= (5,3))

print(var4)

[[3 6 4]
 [4 1 8]
 [6 2 1]
 [6 2 5]
 [2 3 5]]


# Data Types

In [ ]:
var = np.array([1, 2, 3, 4, 5])

print("Data Type: ", var.dtype)

Data Type:  int32


In [ ]:
var = np.array([1.0 , 1.2, 1.3, 1.4, 1.5])

print("Data Type: ", var.dtype)

Data Type:  float64


In [ ]:
var = np.array(["a", "e", "i", "o", "u"])

print("Data Type: ", var.dtype)

Data Type:  <U1


In [ ]:
var = np.array(["a", 2, "i", 4, "u"])

print("Data Type: ", var.dtype)

Data Type:  <U11


In [ ]:
x = np.array([1, 2, 3, 4])

print("Data Type: ", x.dtype)

Data Type:  int32


In [ ]:
# TYpe Casting
x = np.array([1, 2, 3, 4], dtype= np.int8)

print("Data Type: ", x.dtype)

Data Type:  int8


In [ ]:
x = np.array([1, 2, 3, 4], dtype= "f")

print("Data Type: ", x.dtype)
print(x)

Data Type:  float32
[1. 2. 3. 4.]


In [ ]:
x2 = np.array([1, 2, 3, 4])

new = np.float32(x2)

print("Data Type: ", x2.dtype)
print("Data Type: ", new.dtype)

print(x2)
print(new)

Data Type:  int32
Data Type:  float32
[1 2 3 4]
[1. 2. 3. 4.]


In [ ]:
# Changing data type
x3 = np.array([1, 2, 3, 4])

new_1 = x3.astype(float)

print(x3)
print(new_1)

[1 2 3 4]
[1. 2. 3. 4.]


# Arithmetic Operation

In [ ]:
# add
var = np.array([1, 2, 3, 4, 5])

var_add = var + 3

print(var_add)

[4 5 6 7 8]


In [ ]:
var1 = np.array([1, 2, 3, 4, 5])
var2 = np.array([1, 2, 3, 4, 5])

var_add = var1 + var2

print(var_add)

[ 2  4  6  8 10]


In [ ]:
# multiply

var = np.array([1, 2, 3, 4, 5])

var_add = var * 3

print(var_add)

[ 3  6  9 12 15]


In [ ]:
# subtract 

var = np.array([1, 2, 3, 4, 5])

var_add = var - 3

print(var_add)

[-2 -1  0  1  2]


In [ ]:
# modulo

var = np.array([1, 2, 3, 4, 5])

var_add = var % 3

print(var_add)

[1 2 0 1 2]


In [ ]:
# divide

var = np.array([1, 2, 3, 4, 5])

var_add = var / 3

print(var_add)

[0.33333333 0.66666667 1.         1.33333333 1.66666667]


In [ ]:
# Using functions to perform arithmetic tasks

var1 = np.array([1, 2, 3, 4, 5])
var2 = np.array([1, 2, 3, 4, 5])

var_add = np.add(var1, var2)


print(var_add)

[ 2  4  6  8 10]


In [ ]:
# reciprocal

var = np.array([1, 2, 3, 4, 5])

var_add = np.reciprocal(var)

print(var_add)

[1 0 0 0 0]


In [ ]:
# In 2-D Array

var21 = np.array([[1, 2, 3, 4, 5]])
var22 = np.array([[1, 2, 3, 4, 5]])

var_add2 = np.add(var21, var22)

print(var_add2)

[[ 2  4  6  8 10]]


In [ ]:
var21 = np.array([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])
var22 = np.array([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])

print(var21)
print()
print(var22)
print()

var_add2 = np.add(var21, var22)

print(var_add2)

[[1 2 3 4 5]
 [1 2 3 4 5]]

[[1 2 3 4 5]
 [1 2 3 4 5]]

[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]


# Arithmetic Functions

In [ ]:
# min and max   and those values positions
var = np.array([1, 2, 3, 4, 5])

var_min = np.min(var)
var_max = np.max(var)

print(var_min, np.argmin(var))
print(var_max, np.argmax(var))

1 0
5 4


In [ ]:
var1 = np.array([[1, 2, 3], [9, 5, 6]])

print(np.min(var1, axis=0))  # axis = 0 means column and 1 means rows
print(np.min(var1, axis=1))

[1 2 3]
[1 5]


In [ ]:
# square root

var = np.array([4, 9, 16, 25, 36])

var_sqrt = np.sqrt(var)
print(var_sqrt)

[2. 3. 4. 5. 6.]


In [ ]:
# sin and cos

var = np.array([4, 9, 16, 25, 36])

var_sin = np.sin(var)
var_cos = np.cos(var)

print(var_sin)
print(var_cos)

[-0.7568025   0.41211849 -0.28790332 -0.13235175 -0.99177885]
[-0.65364362 -0.91113026 -0.95765948  0.99120281 -0.12796369]


In [ ]:
# cumsum

var = np.array([4, 9, 16, 25, 36])

var_cumsum = np.cumsum(var)
print(var_cumsum)

[ 4 13 29 54 90]


# Shape and Reshape

In [ ]:
# SHAPE

var = np.array([[1, 2], [1, 2]])

print(var)
print()
print(var.shape)

[[1 2]
 [1 2]]

(2, 2)


In [ ]:
var1 = np.array([1, 2, 3, 4], ndmin=7)

print(var1)
print(var1.ndim)
print()
print(var1.shape)

[[[[[[[1 2 3 4]]]]]]]
7

(1, 1, 1, 1, 1, 1, 4)


In [ ]:
# RESHAPE

var2 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(var2)
print(var.ndim)
print()

var_re = var2.reshape((3, 3))
print(var_re)
print(var_re.ndim)

[1 2 3 4 5 6 7 8 9]
2

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2


In [ ]:
var3 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(var3)
print(var3.ndim)
print()

var_re2 = var3.reshape(2, 3, 2)

print(var_re2)
print(var_re2.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3


In [ ]:
var3 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

print(var3)
print(var3.ndim)
print()

var_re2 = var3.reshape(2, 3, 2)

print(var_re2)
print(var_re2.ndim)
print()

one = var_re2.reshape(-1)
print(one)
print(one.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1


# Broadcasting

In [ ]:
var1 = np.array([1, 2, 3, 4])

var2 = np.array([1, 2, 3])

print(var1 + var2)  # error

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [ ]:
# dimension should be same if not that then one value should be same i.e. row or columns
var1 = np.array([1, 2, 3, 4])
print(var1)
print(var1.ndim)
print(var1.shape)
print()

var2 = np.array([[1], [2], [3]])
print(var2)
print(var2.ndim)
print(var2.shape)
print()

print(var1 + var2)
print((var1+var2).ndim)
print((var1+var2).shape)

[1 2 3 4]
1
(4,)

[[1]
 [2]
 [3]]
2
(3, 1)

[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]
2
(3, 4)


In [ ]:
a = np.array([[1], [2]])
print(a.shape)


b = np.array([[1, 2, 3], [1, 2, 3]])
print(b.shape)

print(a+b)

(2, 1)
(2, 3)
[[2 3 4]
 [3 4 5]]


# Indexing & Slicing

In [ ]:
# Indexing

var1 = np.array([1, 2, 3, 4, 5])
#                0  1  2  3  4
#                    -3 -2  -1
print(var1[2])
print(var1[-3])


3
3


In [ ]:
var2 = np.array([[7, 8, 9], [4, 5, 6]])

print(var2)
print(var2.ndim)
print()

print(var2[0,1])   # row no, element no

[[7 8 9]
 [4 5 6]]
2

8


In [ ]:
var3 = np.array([[[7, 8, 9], [4, 5, 6], [1, 2, 3]]])

print(var3)
print(var3.ndim)
print()

print(var3[0,1,1])  # slice no, row no, element no

[[[7 8 9]
  [4 5 6]
  [1 2 3]]]
3

5


In [ ]:
# Slicing

var = np.array([1, 2, 3, 4, 5, 6, 7])

print(var)
print()
print(var[1:5:2])   # starting point  : stopping point : step

print(var[2:])  # 3 onwards

print(var[:5])  # before 6

print(var[::2])  # everything with jump of 2 steps

print(var[::-1])  # reverse everything



[1 2 3 4 5 6 7]

[2 4]
[3 4 5 6 7]
[1 2 3 4 5]
[1 3 5 7]
[7 6 5 4 3 2 1]


In [ ]:
var1 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])

print(var1)
print(var1.ndim)
print()

print(var1[1,1:5:2])   # slice no. ,   starting point : stopping point : steps

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
2

[7 9]


# Iteration

In [ ]:
var = np.array([1, 2, 3 , 4, 5, 6, 7])
print(var)
print()

for i in var:
    print(i)

[1 2 3 4 5 6 7]

2
3


In [ ]:
var1 = np.array([[1, 2, 3, 4, 5], [1, 2, 3 ,4, 5]])
print(var1)
print()

for j in var1:
    print(j)   # two blocks will br printed

print()

for k in var1:
    for l in k:
        print(l)


[[1 2 3 4 5]
 [1 2 3 4 5]]

[1 2 3 4 5]
[1 2 3 4 5]

1
2
3
4
5
1
2
3
4
5


In [ ]:
var2 = np.array([[[1,2,3,4], [1,2,3,4], [1,2,3,4]]])
print(var2)
print()

for i in var2:
    for j in i:
        for k in j:
            print(k)

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]

1
2
3
4
1
2
3
4
1
2
3
4


In [ ]:
# Using nditer function


var2 = np.array([[[1,2,3,4], [1,2,3,4], [1,2,3,4]]])
print(var2)
print()

for i in np.nditer(var2):    # gets data
    print(i)

print()

for i,d in np.ndenumerate(var2):  # gets data and index number at once
    print(i,d)

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]

1
2
3
4
1
2
3
4
1
2
3
4

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 1, 0) 1
(0, 1, 1) 2
(0, 1, 2) 3
(0, 1, 3) 4
(0, 2, 0) 1
(0, 2, 1) 2
(0, 2, 2) 3
(0, 2, 3) 4


# Copy vs View

In [ ]:
var = np.array([1, 2, 3, 4])

copy = var.copy()

var[1] = 20

print("Var:", var)
print("Copy:", copy)

Var: [ 1 20  3  4]
Copy: [1 2 3 4]


In [ ]:
a = np.array([5, 4, 3, 2, 1])

view = a.view()

a[1] = 40

print("a:", a)
print("view:", view)

a: [ 5 40  3  2  1]
view: [ 5 40  3  2  1]


# Joining & Split in NumPy Arrays

In [ ]:
# Join Array

var = np.array([1, 2, 3, 4])
var1 = np.array([6, 7, 8, 9])

arr = np.concatenate((var, var1))

print(arr)

[1 2 3 4 6 7 8 9]


In [ ]:
# 2-D Array
a = np.array([[1, 2], [3, 4]])
b = np.array([[6, 7], [8, 9]])

arr = np.concatenate((a, b), axis=1)   # 0 = row ||  1 = column

print(a)
print()
print(b)
print()
print(arr)

[[1 2]
 [3 4]]

[[6 7]
 [8 9]]

[[1 2 6 7]
 [3 4 8 9]]


In [ ]:
var = np.array([1, 2, 3, 4])
var1 = np.array([6, 7, 8, 9])

arr = np.stack((var, var1), axis=1)

print(arr)

[[1 6]
 [2 7]
 [3 8]
 [4 9]]


In [ ]:
# h stack
var = np.array([1, 2, 3, 4])
var1 = np.array([6, 7, 8, 9])

arr = np.hstack((var, var1))


print(arr)

[1 2 3 4 6 7 8 9]


In [ ]:
# v stack
var = np.array([1, 2, 3, 4])
var1 = np.array([6, 7, 8, 9])

arr = np.vstack((var, var1))

print(arr)


[[1 2 3 4]
 [6 7 8 9]]


In [ ]:
# d stack
var = np.array([1, 2, 3, 4])
var1 = np.array([6, 7, 8, 9])

arr = np.dstack((var, var1))

print(arr)

[[[1 6]
  [2 7]
  [3 8]
  [4 9]]]


In [ ]:
# All combined

var = np.array([1, 2, 3, 4])
var1 = np.array([6, 7, 8, 9])

arr = np.stack((var, var1), axis=1)
arr1 = np.hstack((var, var1))  # row   or axis 0
arr2 = np.vstack((var, var1))  # columns   or axis 1
arr3 = np.dstack((var, var1))  # height
 

print(arr)
print()
print(arr1)
print()
print(arr2)
print()
print(arr3)

[[1 6]
 [2 7]
 [3 8]
 [4 9]]

[1 2 3 4 6 7 8 9]

[[1 2 3 4]
 [6 7 8 9]]

[[[1 6]
  [2 7]
  [3 8]
  [4 9]]]


In [ ]:
# Split Array

var = np.array([1, 2, 3, 4, 5, 6])

print(var)
print()

split_arr = np.array_split(var, 3)
print(split_arr)
print()
print(split_arr[0])

[1 2 3 4 5 6]

[array([1, 2]), array([3, 4]), array([5, 6])]

[1 2]


In [ ]:
# 2-D Array
var1 = np.array([[1, 2], [3, 4], [5, 6]])

print(var1)
print()

split_arr1 = np.array_split(var1, 3)
split_arr2 = np.array_split(var1, 3, axis=1)

print(split_arr1)
print()
print(split_arr2)
print()
print(split_arr1[0])

[[1 2]
 [3 4]
 [5 6]]

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]

[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]]), array([], shape=(3, 0), dtype=int32)]

[[1 2]]


# NumPy Arrays Functions

In [ ]:
# Search

var = np.array([1, 2, 3, 4, 5, 3, 4, 2, 1, 6, 4, 3, 7])
var1 = np.array([4, 2, 3, 4, 2, 6, 8, 7])


x = np.where(var == 3)

y = np.where(var1 % 2 == 0)


print(x)
print(y)

(array([ 2,  5, 11], dtype=int64),)
(array([0, 1, 3, 4, 5, 6], dtype=int64),)


In [ ]:
var2 = np.array([1, 2, 3, 4, 8, 9, 10])


z = np.searchsorted(var2, [5, 6, 7], side="left")

print(z)

[4 4 4]


In [ ]:
# Sort

var = np.array([5, 1, 8, 3, 4, 2, 1, 6, 10, 4, 3, 7])

var1 = np.array(["b", "z", "a", "x", "c", "y"])

print(np.sort(var))
print(np.sort(var1))





[ 1  1  2  3  3  4  4  5  6  7  8 10]
['a' 'b' 'c' 'x' 'y' 'z']


In [ ]:
var2 = np.array([[2, 3, 1], [11, 10, 12], [9, 4, 8]])

print(np.sort(var2))

[[ 1  2  3]
 [10 11 12]
 [ 4  8  9]]


In [ ]:
# Filter Array

var = np.array(["a", "s", "i", "d", "o", "x", "e", "u"])

f = [True, False, True, False, True, False, True, True]

new_a = var[f]

print(new_a)
print(type(new_a))

['a' 'i' 'o' 'e' 'u']
<class 'numpy.ndarray'>


In [ ]:
# Shuffle

var = np.array([1, 2, 3, 4, 5])

np.random.shuffle(var)

print(var)

[3 1 4 5 2]


In [ ]:
# Unique

var = np.array([1, 2, 1, 3, 4, 3, 2, 5, 6, 4, 2, 1])

unique_var = np.unique(var, return_index= True)

print(unique_var)

(array([1, 2, 3, 4, 5, 6]), array([0, 1, 3, 4, 7, 8], dtype=int64))


In [ ]:
# Resize

var1 = np.array([1, 2, 3, 4, 5, 6])

y = np.resize(var1, (2, 3))     # variable, (rows, column)
 
print(y)

[[1 2 3]
 [4 5 6]]


In [ ]:
# Flatten

var1 = np.array([1, 2, 3, 4, 5, 6])

y = np.resize(var1, (2, 3))  
print(y)
print()

print(y.flatten(order='f'))     # f = column_based  and c = row focused

print(np.ravel(y, order = "f"))

[[1 2 3]
 [4 5 6]]

[1 4 2 5 3 6]
[1 4 2 5 3 6]


In [ ]:
arr = np.array([3, 1, 2, 5, 4])

indices = np.argsort(arr)    # if placed in this way sorted array will get displayed
print(indices)

[1 2 0 4 3]


# Insert and Delete

In [ ]:
# Insert

var = np.array([1, 2, 3, 4, 5])

print(var)
print(type(var))


np.insert(var, 5, 6)       # variable, index number, inserting value
np.insert(var, (4, 5), 7)

[1 2 3 4 5]
<class 'numpy.ndarray'>


array([1, 2, 3, 4, 7, 5, 7])

In [ ]:
var1 = np.array([[1, 2, 3], [1, 2, 3]])

v1_row = np.insert(var1, 2, 6, axis = 0)
v1_col = np.insert(var1, 2, 6, axis = 1)  # variable, index number, inserting value, axis

print(v1_row)
print()
print(v1_col)

[[1 2 3]
 [1 2 3]
 [6 6 6]]

[[1 2 6 3]
 [1 2 6 3]]


In [ ]:
# append

var = np.array([1, 2, 3, 4, 5])

a = np.append(var, 6.5)

print(a)

[1.  2.  3.  4.  5.  6.5]


In [ ]:
var1 = np.array([[1, 2, 3], [4, 5, 6]])

v1 = np.append(var1, [[7, 8, 9]], axis=0)

print(v1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# Delete

var = np.array([1, 2, 3, 4, 5])

print(var)
print()

d = np.delete(var1, 2)
print(d)

[1 2 3 4 5]

[1 2 4 5 6]


# Matrix in Numpy Arrays

In [ ]:
# matrix
var_max = np.matrix([[1, 2, 3], [1, 2, 3]])

# array
var_arr = np.array([[1, 2, 3], [1, 2, 3]])

print(var_max)
print(type(var_max))
print()
print(var_arr)
print(type(var_arr))

[[1 2 3]
 [1 2 3]]
<class 'numpy.matrix'>

[[1 2 3]
 [1 2 3]]
<class 'numpy.ndarray'>


In [ ]:
# addition & subtraction
a = np.matrix([[1, 2], [1, 2]])
b = np.matrix([[1, 2], [1, 2]])

print(a)
print(type(a))
print()
print(a + b)
print()
print(a-b)

[[1 2]
 [1 2]]
<class 'numpy.matrix'>

[[2 4]
 [2 4]]

[[0 0]
 [0 0]]


In [ ]:
# dot function
a = np.matrix([[1, 2], [1, 2]])
b = np.matrix([[1, 2], [1, 2]])

print(a)
print(b)
print(type(a))
print()
print(a.dot(b))

[[1 2]
 [1 2]]
[[1 2]
 [1 2]]
<class 'numpy.matrix'>

[[3 6]
 [3 6]]


# Matrix Function in NumPy Arrays

In [101]:
# Transpose

var = np.matrix([[1, 2, 3], [4, 5, 6]])
print(var)
print()

print(np.transpose(var))
print()
print(var.T)

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]


In [105]:
# Swapaxes
var = np.matrix([[1, 2, 3], [4, 5, 6]])
print(var)
print()

print(np.swapaxes(var, 0, 1))


[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]


In [106]:
var1 = np.matrix([[1, 2], [3, 4]])
print(var1)
print()
print(np.swapaxes(var1, 0, 1))

[[1 2]
 [3 4]]

[[1 3]
 [2 4]]


In [110]:
# Inverse

var = np.matrix([[1, 2], [3, 4]])
print(var)
print()

print(np.linalg.inv(var))

[[1 2]
 [3 4]]

[[-2.   1. ]
 [ 1.5 -0.5]]


In [122]:
# Power

var = np.matrix([[1, 2], [3, 4]])
print(var)
print()


print(np.linalg.matrix_power(var, 2))
print()
print(np.linalg.matrix_power(var, 0))
print()
print(np.linalg.matrix_power(var, -2))

[[1 2]
 [3 4]]

[[ 7 10]
 [15 22]]

[[1 0]
 [0 1]]

[[ 5.5  -2.5 ]
 [-3.75  1.75]]


In [124]:
# Determinant

var = np.matrix([[1, 2, 3], [3, 4, 3], [1, 2, 3]])
print(var)
print()

print(np.linalg.det(var))

[[1 2 3]
 [3 4 3]
 [1 2 3]]

0.0
